export const actionTypes = {
  START_FETCHING_MENU_BUSINESS_TWO: 'START_FETCHING_MENU_BUSINESS_TWO',
  FETCHED_MENU_BUSINESS_TWO: 'FETCHED_MENU_BUSINESS_TWO',
  FETCH_ERROR_MENU_BUSINESS_TWO: 'FETCH_ERROR_MENU_BUSINESS_TWO'
}