export const actionTypes = {
  START_FETCHING_MENU_MUSIC_TWO: 'START_FETCHING_MENU_MUSIC_TWO',
  FETCHED_MENU_MUSIC_TWO: 'FETCHED_MENU_MUSIC_TWO',
  FETCH_ERROR_MENU_MUSIC_TWO: 'FETCH_ERROR_MENU_MUSIC_TWO'
}