export const BlogOneActionTypes = {

  BLOG_ONE_PAGES: 'BLOG_ONE_PAGES',
  BLOG_ONE_NEXT_PAGE: 'BLOG_ONE_NEXT_PAGE',
  BLOG_ONE_PREV_PAGE: 'BLOG_ONE_PREV_PAGE',
  BLOG_ONE_BACK_TO_PAGES: 'BLOG_ONE_BACK_TO_PAGES',
  BLOG_ONE_PAGE_RESET: 'BLOG_ONE_PAGE_RESET',

  BLOG_ONE_SELECTED_MONTH: 'BLOG_ONE_SELECTED_MONTH',
  BLOG_ONE_SELECTED_YEAR: 'BLOG_ONE_SELECTED_YEAR'

}