export const actionTypes = {
  START_FETCHING_MENU_BUSINESS_ONE: 'START_FETCHING_MENU_BUSINESS_ONE',
  FETCHED_MENU_BUSINESS_ONE: 'FETCHED_MENU_BUSINESS_ONE',
  FETCH_ERROR_MENU_BUSINESS_ONE: 'FETCH_ERROR_MENU_BUSINESS_ONE'
}