export const actionTypes = {
  START_FETCHING_MENU_BLOG_ONE: 'START_FETCHING_MENU_BLOG_ONE',
  FETCHED_MENU_BLOG_ONE: 'FETCHED_MENU_BLOG_ONE',
  FETCH_ERROR_MENU_BLOG_ONE: 'FETCH_ERROR_MENU_BLOG_ONE'
}