export const actionTypes = {

  BLOG_ONE_POPULAR_FETCHING: 'BLOG_ONE_POPULAR_FETCHING',
  BLOG_ONE_POPULAR_FETCHED: 'BLOG_ONE_POPULAR_FETCHED',
  BLOG_ONE_POPULAR_FETCH_ERROR: 'BLOG_ONE_POPULAR_FETCH_ERROR',

}