export const BlogSevenActionTypes = {

  BLOG_SEVEN_PAGES: 'BLOG_SEVEN_PAGES',
  BLOG_SEVEN_NEXT_PAGE: 'BLOG_SEVEN_NEXT_PAGE',
  BLOG_SEVEN_PREV_PAGE: 'BLOG_SEVEN_PREV_PAGE',
  BLOG_SEVEN_BACK_TO_PAGES: 'BLOG_SEVEN_BACK_TO_PAGES',
  BLOG_SEVEN_PAGE_RESET: 'BLOG_SEVEN_PAGE_RESET',

  BLOG_SEVEN_SELECTED_MONTH: 'BLOG_SEVEN_SELECTED_MONTH',
  BLOG_SEVEN_SELECTED_YEAR: 'BLOG_SEVEN_SELECTED_YEAR'

}