export const actionTypes = {

  BLOG_THREE_POPULAR_FETCHING: 'BLOG_THREE_POPULAR_FETCHING',
  BLOG_THREE_POPULAR_FETCHED: 'BLOG_THREE_POPULAR_FETCHED',
  BLOG_THREE_POPULAR_FETCH_ERROR: 'BLOG_THREE_POPULAR_FETCH_ERROR',

}