export const actionTypes = {
  START_FETCHING_TOUR: 'START_FETCHING_TOUR',
  FETCHED_TOUR: 'FETCHED_TOUR',
  FETCH_ERROR_TOUR: 'FETCH_ERROR_TOUR',


  START_FETCHING_TOUR_DETAILS: 'START_FETCHING_TOUR_DETAILS',
  FETCHED_TOUR_DETAILS: 'FETCHED_TOUR_DETAILS',
  FETCH_ERROR_TOUR_DETAILS: 'FETCH_ERROR_TOUR_DETAILS',

  HIDE_TOUR_PLAN: 'HIDE_TOUR_PLAN'
}