export const actionTypes = {

  START_FETCHING_NEWS_LATEST: "FETCHING_NEWS_LATEST",
  FETCHED_NEWS_LATEST: "FETCHED_NEWS_LATEST",
  FETCHE_NEWS_LATEST_ERROR: "FETCHE_NEWS_LATEST_ERROR",

  START_FETCHING_LANDING_PAGE: "FETCHING_LANDING_PAGE",
  FETCHED_LANDING_PAGE: "FETCHED_LANDING_PAGE",
  FETCHE_LANDING_PAGE_ERROR: "FETCHE_LANDING_PAGE_ERROR"

}