export const ActionMusicThreeTypes = {

  FETCHING_MUSIC_THREE_ALBUM: 'FETCHING_MUSIC_THREE_ALBUM',
  FETCHED_MUSIC_THREE_ALBUM: 'FETCH_MUSIC_THREE_ALBUM',
  FETCH_MUSIC_THREE_ERROR: 'FETCH_MUSIC_THREE_ERROR',

  FETCHING_MUSIC_THREE_TRACK_LIST: 'FETCHING_MUSIC_THREE_TRACK_LIST',
  FETCHED_MUSIC_THREE_TRACK_LIST: 'FETCHED_MUSIC_THREE_TRACK_LIST',
  FETCH_MUSIC_THREE_TRACK_LIST_ERROR: 'FETCH_MUSIC_THREE_TRACK_LIST_ERROR',

  MUSIC_THREE_PLAY_THE_TRACK: 'MUSIC_THREE_PLAY_THE_TRACK'

}
