export const actionTypes = {
  START_FETCHING_MENU_BLOG_TWO: 'START_FETCHING_MENU_BLOG_TWO',
  FETCHED_MENU_BLOG_TWO: 'FETCHED_MENU_BLOG_TWO',
  FETCH_ERROR_MENU_BLOG_TWO: 'FETCH_ERROR_MENU_BLOG_TWO'
}