export const actionTypes = {

  BLOG_THREE_TAXONOMY_FETCHING: 'BLOG_THREE_TAXONOMY_FETCHING',
  BLOG_THREE_TAXONOMY_FETCHED: 'BLOG_THREE_TAXONOMY_FETCHED',
  BLOG_THREE_TAXONOMY_FETCH_ERROR: 'BLOG_THREE_TAXONOMY_FETCH_ERROR',

}