export const actionTypes = {

  BLOG_TWO_READ_MORE_FETCHING: 'BLOG_TWO_READ_MORE_FETCHING',
  BLOG_TWO_READ_MORE_FETCHED: 'BLOG_TWO_READ_MORE_FETCHED',
  BLOG_TWO_READ_MORE_FETCH_ERROR: 'BLOG_TWO_READ_MORE_FETCH_ERROR',

}