export const actionTypes = {

  START_FETCHING: 'START_FETCHING',
  FETCHED: 'FETCHED',
  FETCH_ERROR: 'FETCH_ERROR',

  START_FETCHING_TRAKCS: 'START_FETCHING_TRACKS',
  FETCHED_TRACKS: 'FETCHED_TRACKS',
  FETCH_ERROR_TRACKS: 'FETCH_ERROR_TRAKCS',

  START_FETCHING_ALBUM: 'START_FETCHING_ALBUM',
  FETCHED_ALBUM: 'FETCHED_ALBUM',
  FETCH_ERROR_ALBUM: 'FETCH_ERROR_ALBUM',

  START_FETCHING_TOUR: 'START_FETCHING_TOUR',
  FETCHED_TOUR: 'FETCHED_TOUR',
  FETCH_ERROR_TOUR: 'FETCH_ERROR_TOUR',


  START_FETCHING_TOUR_DETAILS: 'START_FETCHING_TOUR_DETAILS',
  FETCHED_TOUR_DETAILS: 'FETCHED_TOUR_DETAILS',
  FETCH_ERROR_TOUR_DETAILS: 'FETCH_ERROR_TOUR_DETAILS',


  SELECT_COLOUR_MODE: 'SELECT_COLOUR_MODE',

  START_PHOTO_FETCHING: 'START_PHOTO_FETCHING',
  PHOTO_FETCHED: 'PHOTO_FETCHED',
  PHOTO_FETCH_ERROR: 'PHOTO_FETCH_ERROR'

}