export const actionTypes = {

  BLOG_THREE_BLOG_FETCHING: 'BLOG_THREE_BLOG_FETCHING',
  BLOG_THREE_BLOG_FETCHED: 'BLOG_THREE_BLOG_FETCHED',
  BLOG_THREE_BLOG_FETCH_ERROR: 'BLOG_THREE_BLOG_FETCH_ERROR',

  BLOG_THREE_SELECTED_MONTH: 'BLOG_THREE_SELECTED_MONTH',
  BLOG_THREE_SELECTED_YEAR: 'BLOG_THREE_SELECTED_YEAR',

  BLOG_THREE_BY_TAXONOMY_FETCHING: 'BLOG_THREE_BY_TAXONOMY_FETCHING',
  BLOG_THREE_BY_TAXONOMY_FETCHED: 'BLOG_THREE_BY_TAXONOMY_FETCHED',
  BLOG_THREE_BY_TAXONOMY_FETCH_ERROR: 'BLOG_THREE_BY_TAXONOMY_FETCH_ERROR',

  BLOG_THREE_SEARCH_FORM: 'BLOG_THREE_SEARCH_FORM'

}