export const actionTypes = {

  BLOG_THREE_READ_MORE_FETCHING: 'BLOG_THREE_READ_MORE_FETCHING',
  BLOG_THREE_READ_MORE_FETCHED: 'BLOG_THREE_READ_MORE_FETCHED',
  BLOG_THREE_READ_MORE_FETCH_ERROR: 'BLOG_THREE_READ_MORE_FETCH_ERROR',

}