export const actionTypes = {

  BLOG_ONE_READ_MORE_FETCHING: 'BLOG_ONE_READ_MORE_FETCHING',
  BLOG_ONE_READ_MORE_FETCHED: 'BLOG_ONE_READ_MORE_FETCHED',
  BLOG_ONE_READ_MORE_FETCH_ERROR: 'BLOG_ONE_READ_MORE_FETCH_ERROR',

}