export const actionTypes = {
  START_FETCHING_MENU_MUSIC_THREE: 'START_FETCHING_MENU_MUSIC_THREE',
  FETCHED_MENU_MUSIC_THREE: 'FETCHED_MENU_MUSIC_THREE',
  FETCH_ERROR_MENU_MUSIC_THREE: 'FETCH_ERROR_MENU_MUSIC_THREE'
}