export const actionTypes = {

  BLOG_THREE_NEWS_FETCHING: 'BLOG_THREE_NEWS_FETCHING',
  BLOG_THREE_NEWS_FETCHED: 'BLOG_THREE_NEWS_FETCHED',
  BLOG_THREE_NEWS_FETCH_ERROR: 'BLOG_THREE_NEWS_FETCH_ERROR',

}