export const actionTypes = {
  START_FETCHING_MENU_MUSIC_ONE: 'START_FETCHING_MENU_MUSIC_ONE',
  FETCHED_MENU_MUSIC_ONE: 'FETCHED_MENU_MUSIC_ONE',
  FETCH_ERROR_MENU_MUSIC_ONE: 'FETCH_ERROR_MENU_MUSIC_ONE'
}