export const actionTypes = {

  SELECT_PROJECT_GROUP_ITEM: 'SELECT_PROJECT_GROUP_ITEM',
  SELECT_COLOUR_MODE: 'SELECT_COLOUR_MODE',

  PLAY_THE_TRACK: 'PLAY_THE_TRACK',
  PAUSE_THE_TRACK: 'PAUSE_THE_TRACK',
  STOP_THE_TRACK: 'STOP_THE_TRACK',

  PLAY_ALL_TRACKS: 'PLAY_ALL_TRACKS',

  PAGINATION: 'PAGINATION',
  GOTOPAGE: 'GOTOPAGE',

  START_FETCHING: 'START_FETCHING',
  FETCHED: 'FETCHED',
  FETCH_ERROR: 'FETCH_ERROR',
  FETCH_ALBUM: 'FETCH_ALBUM',




}