export const actionTypes = {

  START_FETCHING: 'START_FETCHING',
  FETCHED: 'FETCHED',
  FETCH_ERROR: 'FETCH_ERROR',


  SELECT_COLOUR_MODE: 'SELECT_COLOUR_MODE',

  START_PHOTO_FETCHING: 'START_PHOTO_FETCHING',
  PHOTO_FETCHED: 'PHOTO_FETCHED',
  PHOTO_FETCH_ERROR: 'PHOTO_FETCH_ERROR',

  GO_BACK_TO_THE_PAGE: 'GO_BACK_TO_THE_PAGE'

}