export const actionTypes = {

  BLOG_ONE_TAXONOMY_FETCHING: 'BLOG_ONE_TAXONOMY_FETCHING',
  BLOG_ONE_TAXONOMY_FETCHED: 'BLOG_ONE_TAXONOMY_FETCHED',
  BLOG_ONE_TAXONOMY_FETCH_ERROR: 'BLOG_ONE_TAXONOMY_FETCH_ERROR',

}