export const actionTypes = {

  BLOG_ONE_BLOG_FETCHING: 'BLOG_ONE_BLOG_FETCHING',
  BLOG_ONE_BLOG_FETCHED: 'BLOG_ONE_BLOG_FETCHED',
  BLOG_ONE_BLOG_FETCH_ERROR: 'BLOG_ONE_BLOG_FETCH_ERROR',

  BLOG_SELECTED_MONTH: 'BLOG_SELECTED_MONTH',
  BLOG_SELECTED_YEAR: 'BLOG_SELECTED_YEAR',

  BLOG_ONE_BY_TAXONOMY_FETCHING: 'BLOG_ONE_BY_TAXONOMY_FETCHING',
  BLOG_ONE_BY_TAXONOMY_FETCHED: 'BLOG_ONE_BY_TAXONOMY_FETCHED',
  BLOG_ONE_BY_TAXONOMY_FETCH_ERROR: 'BLOG_ONE_BY_TAXONOMY_FETCH_ERROR',

  BLOG_ONE_SEARCH_FORM: 'BLOG_ONE_SEARCH_FORM'

}