export const actionTypes = {
  START_FETCHING_MENU_BLOG_THREE: 'START_FETCHING_MENU_BLOG_THREE',
  FETCHED_MENU_BLOG_THREE: 'FETCHED_MENU_BLOG_THREE',
  FETCH_ERROR_MENU_BLOG_THREE: 'FETCH_ERROR_MENU_BLOG_THREE'
}