export const actionTypes = {

  START_FETCHING_TRAKCS: 'START_FETCHING_TRACKS',
  FETCHED_TRACKS: 'FETCHED_TRACKS',
  FETCH_ERROR_TRACKS: 'FETCH_ERROR_TRAKCS',

  START_FETCHING_ALBUM: 'START_FETCHING_ALBUM',
  FETCHED_ALBUM: 'FETCHED_ALBUM',
  FETCH_ERROR_ALBUM: 'FETCH_ERROR_ALBUM',

}