export const actionTypes = {

  BLOG_TWO_BLOG_FETCHING: 'BLOG_TWO_BLOG_FETCHING',
  BLOG_TWO_BLOG_FETCHED: 'BLOG_TWO_BLOG_FETCHED',
  BLOG_TWO_BLOG_FETCH_ERROR: 'BLOG_TWO_BLOG_FETCH_ERROR',

  BLOG_TWO_SELECTED_MONTH: 'BLOG_TWO_SELECTED_MONTH',
  BLOG_TWO_SELECTED_YEAR: 'BLOG_TWO_SELECTED_YEAR',


  BLOG_TWO_BY_TAXONOMY_FETCHING: 'BLOG_TWO_BY_TAXONOMY_FETCHING',
  BLOG_TWO_BY_TAXONOMY_FETCHED: 'BLOG_TWO_BY_TAXONOMY_FETCHED',
  BLOG_TWO_BY_TAXONOMY_FETCH_ERROR: 'BLOG_TWO_BY_TAXONOMY_FETCH_ERROR',

  BLOG_TWO_SEARCH_FORM: 'BLOG_TWO_SEARCH_FORM'

}